#!/usr/bin/env sh

if [ -x /usr/libexec/path_helper ]; then
    eval $(/usr/libexec/path_helper -s)
fi

mode=$1
target=$2
if [ "$1" = "run" ]; then
  ${2} &
  proc_pid=$!
  tauri_pid=$PPID
  while true
  do
    if ! ps -p $tauri_pid > /dev/null
    then
      kill -9 $proc_pid
      exit 0
    fi
    sleep 1
  done
fi
