#!/usr/bin/env sh

mode=$1
target=$2
if [ "$1" = "run" ]; then
  ${2} --port 0 &
  proc_pid=$!
  tauri_pid=$PPID
  while true
  do
    if ! ps -p $tauri_pid > /dev/null
    then
      kill -9 $proc_pid
      exit 0
    fi
    sleep 1
  done
fi
